namespace Lumoria.Runtime {
    private const string DXVK_CONFIG_MARKER = "# Generated by Lumoria.";

    public void apply_dxvk_config (
        string prefix_root,
        Models.PrefixEntry entry,
        Models.Entrypoint? entrypoint,
        WineEnv env,
        RuntimeLog logger
    ) {
        var config_path = dxvk_config_path (prefix_root);
        var active = is_dxvk_active (entry, entrypoint);
        var lines = build_dxvk_config_lines (entry, logger);

        if (!entry.advanced_dxvk || !active || lines.size == 0) {
            cleanup_dxvk_config (config_path, logger);
            return;
        }

        var content = new Gee.ArrayList<string> ();
        content.add (DXVK_CONFIG_MARKER + " Changes may be overwritten.");
        content.add_all (lines);
        try {
            Utils.ensure_dir (Path.get_dirname (config_path));
            FileUtils.set_contents (config_path, string.joinv ("\n", Utils.arraylist_to_strv (content)) + "\n");
            env.set_var ("DXVK_CONFIG_FILE", config_path);
            logger.typed (LogType.DEBUG, "wrote DXVK config: %s".printf (config_path));
        } catch (Error e) {
            logger.typed (LogType.WARN, "Failed to write DXVK config: %s".printf (e.message));
        }
    }

    public void cleanup_managed_dxvk_config (
        string prefix_root,
        RuntimeLog? logger = null
    ) {
        cleanup_dxvk_config (dxvk_config_path (prefix_root), logger);
    }

    private string dxvk_config_path (string prefix_root) {
        return Path.build_filename (
            prefix_root,
            "lumoria",
            "dxvk",
            "dxvk.conf"
        );
    }

    private Gee.ArrayList<string> build_dxvk_config_lines (
        Models.PrefixEntry entry,
        RuntimeLog logger
    ) {
        var lines = new Gee.ArrayList<string> ();

        if (entry.dxvk_show_fps) {
            lines.add ("dxvk.hud = fps");
        }
        append_dxvk_int_line (
            lines,
            "d3d9.samplerAnisotropy",
            entry.dxvk_sampler_anisotropy,
            0,
            16,
            logger
        );
        append_dxvk_int_line (
            lines,
            "d3d9.maxFrameRate",
            entry.dxvk_max_frame_rate,
            int.MIN,
            int.MAX,
            logger
        );
        append_dxvk_int_line (
            lines,
            "d3d9.presentInterval",
            entry.dxvk_sync_interval,
            0,
            int.MAX,
            logger
        );

        var custom = entry.dxvk_config_custom.strip ();
        if (custom != "") {
            if (lines.size > 0) lines.add ("");
            lines.add ("# Custom entries");
            foreach (var line in custom.split ("\n")) {
                lines.add (line);
            }
        }

        return lines;
    }

    private void append_dxvk_int_line (
        Gee.ArrayList<string> lines,
        string key,
        string value,
        int min,
        int max,
        RuntimeLog logger
    ) {
        var trimmed = value.strip ();
        if (trimmed == "") return;

        int parsed;
        if (!int.try_parse (trimmed, out parsed) || parsed < min || parsed > max) {
            logger.typed (LogType.WARN, "Skipping invalid DXVK config value for %s: %s".printf (key, value));
            return;
        }
        lines.add ("%s = %s".printf (key, parsed.to_string ()));
    }

    private void cleanup_dxvk_config (string config_path, RuntimeLog? logger) {
        if (!FileUtils.test (config_path, FileTest.EXISTS)) return;

        if (FileUtils.unlink (config_path) == 0) {
            if (logger != null) logger.typed (LogType.DEBUG, "removed DXVK config: %s".printf (config_path));
        } else {
            if (logger != null) logger.typed (LogType.WARN, "Failed to remove DXVK config: %s".printf (config_path));
        }
    }
}
